#!/usr/bin/python
import os
import scipy.integrate as integrate
import scipy.special as special
from numpy import log, inf, inf

#TODO read parameters from the command line

#Reminder: With m substreams,
# 	   E = alpha(m)*m*m*(sum (i->m) [ 2^( - max (zeroes) ) ] ) 
#    With: alpha(m) = m * (integrate (0 -> infinite) [ ( log2((2+u)/(1+u)) )^m ] du ) ^ -1  
#    Suggested alpha values:
#	alpha (16) = 0.673
#	alpha (32) = 0.697 
#	alpha (64) = 0.709 
#	alpha (m)  = 0.7213/(1+1.079/m) for m >= 128

p=8
m=2**p

def calc_alpha(m): #Single call, can be substituted on compilation to insert alpha's value in the p4 program
	if   m == 16:
		return 0.673
	elif m == 32:
		return 0.697
	elif m == 64:
		return 0.709
	else:
		def integrand(u,m):
			return  ( log ((2+u)/(1+u))/ log(2) )**m 
		integrale = integrate.quad(integrand, 0, +inf, args=(m))
		print("alpha:", 1/(m*integrale[0]))
		return(1/(m*integrale[0]))

last_m=-1
alpha=1
def calc_estimate(m,zeroes):
	if last_m!=m:
		alpha = calc_alpha(m)
		last_m=m
	sum=0
	for i in range(m):
		sum=sum+2**(-(zeroes[i])) 
	res=alpha*m*m/sum
	print("sum:",sum, "m:",m)
	return(res,alpha)

r5= [7, 6, 7, 4, 9, 8, 5, 7, 3, 5, 6, 6, 5, 7, 7, 5, 4, 3, 5, 5, 5, 6, 6, 4, 6, 7, 5, 4, 6, 4, 8, 4, 11, 7, 7, 7, 7, 5, 7, 4, 5, 7, 6, 5, 6, 7, 4, 4, 5, 9, 6, 4, 5, 6, 6, 5, 6, 9, 8, 6, 6, 10, 7, 6, 7, 8, 6, 6, 7, 7, 10, 8, 9, 7, 8, 5, 4, 5, 5, 6, 5, 4, 4, 6, 6, 6, 7, 7, 5, 7, 6, 6, 8, 8, 7, 5, 8, 6, 6, 6, 6, 6, 6, 5, 6, 6, 11, 4, 7, 5, 6, 6, 9, 8, 6, 6, 5, 6, 9, 4, 9, 7, 5, 8, 5, 5, 6, 6, 5, 5, 5, 8, 9, 9, 5, 7, 5, 8, 7, 4, 6, 8, 6, 5, 5, 8, 6, 6, 4, 7, 5, 5, 6, 5, 4, 7, 10, 7, 6, 11, 6, 8, 7, 4, 4, 5, 7, 8, 3, 7, 9, 6, 6, 6, 6, 4, 4, 6, 4, 8, 4, 5, 6, 6, 6, 6, 9, 7, 5, 3, 7, 8, 8, 6, 4, 7, 6, 6, 7, 4, 5, 7, 7, 6, 6, 6, 4, 6, 6, 6, 6, 5, 6, 6, 9, 5, 10, 4, 7, 5, 7, 5, 7, 4, 9, 5, 11, 6, 5, 7, 6, 4, 9, 4, 6, 9, 4, 5, 8, 4, 8, 6, 6, 9, 6, 10, 6, 4, 4, 7, 6, 7, 6, 8, 6, 9]

(res,alpha)=calc_estimate(m,r5)
print(res)
